### PR TITLE
Remove console.log JS statements

### PR DESCRIPTION
**Pull request by chukShirley**
These are not needed/useful in production.

### CODE REVIEW

**Review by elijahlofgren — COMMENTED** [review]
Thanks for the cleanup!

**Comment by chukShirley** [comment]
Will rebase...

**Comment by elijahlofgren** [comment]
Looks like there are conflicts, so I can't auto-merge. Sorry, if I caused by merging in wrong order. Thanks again for all your help on this!

**Comment by chukShirley** [comment]
@elijahlofgren Rebased and ready to merge

**Pull request merged**
